all:
	pdflatex abmus-abm_uncertainty.tex
	bibtex abmus-abm_uncertainty
	pdflatex abmus-abm_uncertainty.tex
	pdflatex abmus-abm_uncertainty.tex

clean:
	rm *.aux *.bbl *.log *.blg *.out *.lof *.lot *.tdo *.ttt *.fff


