---
title: "NativeModel Results."
date: '`r format(Sys.time(), "%d %B, %Y (%H:%M)")`'
output:
  html_document: 
    toc: yes
    pandoc_args: [
      "+RTS", "-K64m", 
      "-RTS"
    ]
fontsize: 10pt
---

# ResultsSummary - **NativeModel**

Analyses the results of the keanu tests when experimenting with parameter estimation (probabilistic model needs to guess a single threshold value ). Relevant files that generate the results: `NativeModel`

# Initialise and load data

```{r initialise, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gtools)
library(ggplot2)
library(hexbin) # (this is called automatically if required, but putting it here ensures it has been installed)
library(gridExtra) # For arranging two grids side by side
#library(reshape2) # for melting (taking wide format and making it narrow)
library(xtable) # for making nice tables


homedir<-"C:/ABM_Uncertainty/dust/Improbable/NativeModel-keanu/results/"
setwd(homedir)

# Find files
samples.files <- grep("Results.*csv", list.files(path = "."), value=TRUE)


if (length(samples.files) != 1) {
  message("Found multiple samples files. Using the most recent one.")
  samples.files <- tail(sort(samples.files), n=1)
}

# Read the file in
samples <- read_csv(samples.files[1], col_names=FALSE)

samples[,ncol(samples)] <- NULL # Last column is NA because I lazily write too many commas

# Truth data are the first line
truth.results <- samples[1,]
samples <- samples[-1,]

```

# Plot results (look at the people per iteration)

## Spaghetti plot

```{r spag.plot, fig.width=11, fig.height=9}
# Define a fucntion to plot the samples
spag_plot <- function(samples, truth) {
  
  x_axis <- 1:ncol(samples)
  sample_col <- alpha("#196fe8", 0.8) # #ADD8E6
  truth_col <- "red"
  
  #create plot
  plot(1, xlim=c(0, max(x_axis)), ylim=c(min(rbind(truth,samples)), max(rbind(truth,samples))), type='l',
       xlab="Number of iterations", ylab = "State" )
  map(1:nrow(samples), function(x) lines(x_axis, samples[x,], type='l', col=sample_col))
  lines(x_axis, truth, type='l', lwd=2, col = truth_col)
  abline(v = c(seq(0, 2000, by=200)), lty=2, col='grey')
  
  if(truth.results[1999] < 0) {
    position <- 'topright'
  } else {
    position <- 'bottomright'
  }
  
  legend(position, c("Sample", "Truth"), lty=c(1,1), lwd=c(2.5,2.5),col=c(sample_col, truth_col))
}


#map2(samples, obIntervals, function(x, obInterval) spag_plot(x, truth, obInterval))
spag_plot(samples, truth.results)

```
