all:
	pdflatex abmus-keanu_probabilistic.tex
	bibtex abmus-keanu_probabilistic
	pdflatex abmus-keanu_probabilistic.tex
	pdflatex abmus-keanu_probabilistic.tex

clean:
	rm *.aux *.bbl *.log *.blg *.out *.lof *.lot *.tdo *.ttt *.fff


