all:
	pdflatex KeanuProbabilistic.tex
	bibtex KeanuProbabilistic
	pdflatex KeanuProbabilistic.tex
	pdflatex KeanuProbabilistic.tex

clean:
	rm *.aux *.bbl *.log *.blg *.out *.lof *.lot *.tdo *.ttt *.fff


